In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn import datasets
from sklearn.model_selection import train_test_split

In [2]:
data = pd.read_csv("./Data/weather.csv")

In [3]:
outlook={'sunny':0, 'overcast':1, 'rainy':2}
tem={'hot':0, 'cool':1, 'mild':2}
hum={'high':0, 'normal':1}
wind={'weak':0, 'strong':1}
data['outlook'],_=pd.factorize(data['outlook'])
data['temperature']=data['temperature'].map(tem)
data['humidity']=data['humidity'].map(hum)
data['wind']=data['wind'].map(wind)

In [4]:
X = data.iloc[:,1:5].values
y = data.iloc[:,-1].values
print(X)
print(y)

[[0 0 0 0]
 [0 0 0 1]
 [1 0 0 0]
 [2 2 0 0]
 [2 1 1 0]
 [2 1 1 1]
 [1 1 1 1]
 [0 2 0 0]
 [0 1 1 0]
 [2 2 1 0]
 [0 2 1 1]
 [1 2 0 1]
 [1 0 1 0]
 [2 2 0 1]]
['no' 'no' 'yes' 'yes' 'yes' 'no' 'yes' 'no' 'yes' 'yes' 'yes' 'yes' 'yes'
 'no']


In [5]:
model = KNeighborsClassifier(n_neighbors = 3, p = 2)
model.fit(X, y)

KNeighborsClassifier(n_neighbors=3)

In [6]:
y_prediction = model.predict(X)
print("Du lieu du doan: ",y_prediction)
print("Du lieu that   : ",y)

Du lieu du doan:  ['no' 'no' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes'
 'yes' 'yes']
Du lieu that   :  ['no' 'no' 'yes' 'yes' 'yes' 'no' 'yes' 'no' 'yes' 'yes' 'yes' 'yes' 'yes'
 'no']


In [7]:
iris = datasets.load_iris()
iris_X = iris.data
iris_y = iris.target

In [8]:
X_train, X_test, y_train, y_test = train_test_split(iris_X, iris_y)

In [9]:
model = KNeighborsClassifier(n_neighbors = 3, p = 2)
model.fit(X_train, y_train)
y_predict = model.predict(X_test)

In [10]:
print ("Du lieu du doan: ", y_predict)
print ("Du lieu that   : ", y_test)

Du lieu du doan:  [1 1 1 1 2 0 2 0 2 2 0 2 1 0 0 2 2 2 2 2 1 2 1 0 2 1 0 1 0 1 2 0 2 2 2 0 2
 2]
Du lieu that   :  [1 1 1 1 2 0 2 0 2 2 0 2 1 0 0 2 2 2 2 2 1 2 1 0 2 1 0 1 0 1 2 0 2 2 1 0 1
 2]


In [11]:
from sklearn.metrics import accuracy_score, confusion_matrix
print('accuracy = ',accuracy_score(y_test, y_predict))


accuracy =  0.9473684210526315


In [12]:
cnf_matrix = confusion_matrix(y_test, y_predict)
print('Confusion matrix:')
print(cnf_matrix)

Confusion matrix:
[[10  0  0]
 [ 0 10  2]
 [ 0  0 16]]
